### ISSUE TITLE
Remove the "file_extensions" section from shared configs / make it optional

### ISSUE THREAD

**Issue by mstr3336** [mstr3336/portrpaths#23]
**Description** 

The `file_extensions` mapping in shared.yaml adds little value /abstraction to the user, but adds an extra layer of maintenance  difficulty in configuring paths.
It should be made non-mandatory, and possibly give a message about being redundant.
**Inputs**

Typical shared.yaml format, but now, 

when building an alias for a filename, 

* instead of 
  * using both `file_names` and `file_exts`, and 
  * searching for a mapping of that alias to an ext in `file_exts`, and 
  * failing if this is not found, 
* it will 
  * search for the mapping in both `file_names` and `file_exts`, and 
  * if the mapping is not found in `file_exts` or returns any of the following: 
     * Empty string `""`, 
     * NA `.na_character`, (Any other representation of NA)
     * NULL
* Will not attempt to concat this ext with the name.

When it does encounter file_extension sections, it will complain that they are deprecated

***Format***

An input file resembling the following

```yaml
parent_components:
- inst
- test_data
- t1
- data
file_names:
  encs: cardi_encs
  diag: cardi_diags
  form: cardi_forms
file_extensions:
  encs: txt
  diag: txt
  form: made_up_ext

```

However, now, we may also see
```yaml
file_names:
  encs: cardi_encs
  diag: cardi_diags
  form: cardi_forms
file_extensions:
  encs: txt
  diag: txt
#  form: made_up_ext

```
