### ISSUE TITLE
Version 2 Interface - Will support branching well 

### ISSUE THREAD

**Issue by mstr3336** [mstr3336/portrpaths#24]
**Description** 

The original interface design is quite rigid, and not as nice as I think it should be.

Moving forward, the `shared.yaml` structure should be redesigned as follows:

**Inputs**

A `shared.yaml` with the following structure:
```yaml

version: 0.0.1.9001 # The previous version will be supported, and is specified with < 0.0.1, or blank
root:
 desc: This is the root
 files:
  - eg_1.txt
  - random_file.txt
  - directory_that_i_dont_care_about
 children:
 - in
 - out
directories:
 in:
  path: input
  desc: A top level folder, sharing its structure with out
  files: 
  - only_in_input.txt
  children:
  - v1
  - v2
  - IO_files
 out:
  path: output
  desc: Output files
  files:
  - only_in_output.txt
  children:
  - v1
  - v2
  - IO_files
 v1:
  path: 01-01-2017
  desc: Extract from the start of 2017
  files:
  - encounters.rds
  - diagnosis.rds
v2:
 path: 09-10-2017
 desc: Extract from 4th quarter of 2017
 files:
 - encounters.rds
 - diagnosis.rds
 - locations.rds
IO_files:
 path: 
 desc: Files that should go in both in and out. Path was intentionally left blank
 files:
 - metadata.txt
 - some_file.txt
 - plot_output.png
```

***Format***

Take note of the version identifier - if missing, will be assumed as the deprecated version initially.
Also note the inclusion of "root", and then a flat structure of identified directories.
Each 'directory' has 4 properties:

* path: the name of this binding on disk
  * This could also be left blank, as in IO_files, indicating that the contents will be placed directly in whatever folder is nesting
* desc: The description of this binding
* files: flat, literal filenames within this directory
* children: identifying strings, referring to the mapped names of other directories/collections.

**Outputs** 

The result, for this case, would be that on running `paths$files`, the user now performs the following to navigate to a variable:
`paths$files$in$v1$encounters.rds`

***Format***

So the above would be a nested tree-like list, whose components get built (Recursively)
so (For a root of C://users/matthew/docs/eg/ )

`paths$files$in$v1$encounters.rds` should return 

`C://users/matthew/docs/eg/input/01-01-2017/encounters.rds`
