### ISSUE TITLE
Version 2 - Remove Obfuscating Abstractions, reduce scope

### ISSUE THREAD

**Issue by mstr3336** [mstr3336/portrpaths#33]
Having used this package for nearly a year, I've had time to reflect on what is useful about it, and what is really not useful. 

The biggest take-away is that most features related to the "shared" config are best-case, not that useful, and at worst case obfuscate data storage/ make it more difficult to coordinate between project members.

The most useful feature (In my experience) has been the "profiles" feature, and hotswapping the root. 

# To Remove

Practically all functionality pertaining to shared path configs

# To Add

## Profile Tracking

Presently, when one swaps between profiles, `portrpaths` will find the selected profile from the list, and then write that back to the root. 

I think also writing the name of the chosen profile would be more useful.

## Profile Hints in Shared Config

If the shared config is to be useful at all, I think that maintaining a list of "official" (ish) profiles, and hinting at their use might be how- 

Something like:

```yaml
profiles:
  hpc_3_month:
    desc: |
     The root directory containing the dataset for the 3 month extract
    path: /project/STEMI/workflows/21_03_2019_3m/
  hpc_bulk_13_14:
    desc: |
     The root directory containing the dataset of the 2 year extract from 
     2013 - 2014
    path: /project/STEMI/workflows/bulk_2013_2014
```

These would be used as suggestions only
