### ISSUE TITLE
Add shared config, for profile hints

### ISSUE THREAD

**Issue by mstr3336** [mstr3336/portrpaths#40]
If the shared config is to be useful at all, I think that maintaining a list of "official" (ish) profiles, and hinting at their use might be how- 

Something like:

```yaml
profiles:
  hpc_3_month:
    desc: |
     The root directory containing the dataset for the 3 month extract
    path: /project/STEMI/workflows/21_03_2019_3m/
  hpc_bulk_13_14:
    desc: |
     The root directory containing the dataset of the 2 year extract from 
     2013 - 2014
    path: /project/STEMI/workflows/bulk_2013_2014
```

These would be used as suggestions only
